language: scala
scala:
- 2.11.11
- 2.12.3
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
before_cache:
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete
script:
- sbt -J-Xmx3g clean
- sbt -J-Xmx3g ++$TRAVIS_SCALA_VERSION coverage test
after_success:
- bash ./git-manage.sh
before_install:
- openssl aes-256-cbc -K $encrypted_92ba9974e60f_key -iv $encrypted_92ba9974e60f_iv
  -in deploy.key.enc -out deploy.key -d
- chmod 600 deploy.key
- eval `ssh-agent -s`
- ssh-add deploy.key
